version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.0
    steps:
      - checkout
      - run:
          name: Install Cake
          command: |
            dotnet tool install -g Cake.Tool
            echo 'export PATH=$PATH:/root/.dotnet/tools' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Build
          command: dotnet cake build.cake --runtime=linux-x64
